# Site settings
title: The Greenhouse
email: hello@thegreenhouse.coach
description: A coaching consultancy for people, teams and ideas. A place where things grow; with the recognition that everything within it has different needs, perspectives, experiences and outcomes.
url: "https://andrew-findlay.github.io"
baseurl: ""

# Business info
business:
  name: "The Greenhouse"
  tagline: "Where growth happens naturally"
  email: "hello@thegreenhouse.coach"
  phone: "+44 (0) 20 7123 4567"
  address: "London, UK"

# Navigation
navigation:
  - title: "About"
    url: "#about"
  - title: "Services"
    url: "#services"
  - title: "Contact"
    url: "#contact"

# Services
services:
  - title: "121 Leadership and Development Coaching"
    description: "Delivering tangible areas of focus, actionable learning and a person-centred experience."
  - title: "Team Development and Coaching"
    description: "Delivering collective and shared areas of focus, actionable learning and a person-centred experience."
  - title: "Strategic Ambitions and Ideas Growth"
    description: "Delivering evidence and insight led ideas and frameworks to take to market, your organisation, your people."

# About cards
about_cards:
  - title: "People-Centred Practice"
    description: "Everything within the greenhouse has different needs, perspectives, experiences and outcomes. We centre people and actively work against systems that harm and oppress."
  - title: "Design Justice & Equity"
    description: "Passionate about dismantling dominant systems through facilitative practice. Centring marginalised and minoritised voices in all creative and strategic work."
  - title: "Intersectional Growth"
    description: "A place where things grow naturally - supporting leaders, teams and ideas through evidence-based facilitation and strategic consultancy that recognises diverse experiences."

# Testimonials - removed as requested

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - README.md